stages:
  - build
  - push
  - update

before_script:


build:
  tags:
    - joomla 
  only:
    refs:
      - main 
  stage: build
  script:
    - |
      docker build -t $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/sstech-joomla-nginx:$CI_PIPELINE_ID .

push:
  tags:
    - joomla 
  only:
    refs:
      - main 
  stage: push
  script:
    - |
      aws configure set aws_access_key_id $ACCESS_KEY; aws configure set aws_secret_access_key $SECRET_KEY; aws configure set default.region $REGION
      aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      docker push $ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/sstech-joomla-nginx:$CI_PIPELINE_ID

update:
  tags:
    - joomla
  only:
    refs:
      - main
  stage: update
  script:
    - |
      aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME 
      kubectl set image deployment/joomla-nginx joomla-nginx=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/sstech-joomla-nginx:$CI_PIPELINE_ID
      kubectl rollout status deployment/joomla-nginx

